version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres
    hostname: localhost
    ports:
      - '5433:${DB_PORT}'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  api:
    container_name: dating_api
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    restart: always

volumes:
  postgres-data:
  pgadmin-data:
